---

- hosts: all
  tasks:
  - name: Make Ansible facts directory
    file:
      path: /etc/ansible/facts.d
      state: directory

  - name: Set fact
    set_fact:
      somevar_fact: true
    when: somevar != ""

  - name: Set fact when somevar is define
    copy:
      dest: /etc/ansible/facts.d/custom.fact
      content: |
        [defaults]
        somevar_fact={{ somevar_fact | default(false) }}

  - name: Re-gather facts
    setup:
      

