---

- hosts: all
  gather_facts: false
  connection: local

  tasks:

  - name: Set fact true
    set_fact:
      my_var: true
      cacheable: True
    when: somevar != "" 

  - name: Set fact false
    set_fact:
      my_var: false
      cacheable: True
    when: somevar == "" and somevar is not defined
