---

- hosts: all
  gather_facts: false
  connection: local

  tasks:

  - name: Set fact true
    set_fact:
      my_var: true
      cacheable: True
    when: somevar != "" and somevar is defined

  - name: Set fact false
    set_fact:
      my_var: false
      cacheable: True
    when: somevar == "" or somevar is not defined
